### ISSUE TITLE
Support for `shortNames` in CRD generation

### ISSUE THREAD

**Issue by tillig** [buehler/dotnet-operator-sdk#271]
**Is your feature request related to a problem? Please describe.**

I'm trying to build an SMI adapter for Istio since the current one is defunct. As part of that, I'm replicating the custom entities in memory and trying to use the original CRD vs my generated one as a way to compare what I've got done.

I noticed [the original CRD](https://github.com/servicemeshinterface/smi-sdk-go/blob/a143f8bc96eccdf5fc8a66d0c1622591104c77e0/crds/split.yaml#L13) has `shortNames` specified, like:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: trafficsplits.split.smi-spec.io
spec:
  group: split.smi-spec.io
  scope: Namespaced
  names:
    kind: TrafficSplit
    listKind: TrafficSplitList
    shortNames:
    - ts
    plural: trafficsplits
    singular: trafficsplit
```

It doesn't seem this is part of the `[KubernetesEntity]` attribute and there's no other place to specify them, so there's no way to add them to the output CRD.

**Describe the solution you'd like**

Some way to specify `shortNames` for generation. I'd be OK if it was one attribute, like...

```c#
[KubernetesEntityShortNames("a", "b", "c")]
public class Entity : CustomKubernetesEntity {}
```

or maybe a single attribute you could apply multiple times...

```c#
[KubernetesEntityShortName("a")]
[KubernetesEntityShortName("a")]
[KubernetesEntityShortName("a")]
public class Entity : CustomKubernetesEntity {}
```

But some way to add that to the generated spec would be cool.

BTW, I was about to jump ship on trying to get a controller running in C# and switch to Go (which I am... not that great at) when I found this _super amazing SDK you have here_ and I have to say, _this is the booooomb_ 💣 . Thanks!
