### ISSUE TITLE
Generated `Deployment` missing `selector`

### ISSUE THREAD

**Issue by tillig** [buehler/dotnet-operator-sdk#274]
**Describe the bug**

A Kubernetes `Deployment` needs a `.spec.selector` so it knows which pods to manage. The [`OperatorGenerator` where this happens](https://github.com/buehler/dotnet-operator-sdk/blob/0fe6c666523199608e9fce5d08a86f71806d12e5/src/KubeOps/Operator/Commands/Generators/OperatorGenerator.cs#L97) is currently missing the `selector`.

**To Reproduce**

1. Create a new controller project.
2. Build and look at the generated `operator/deployment.yaml`.

**Expected behavior**

What you get:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator-deployment: my-controller
  name: operator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        operator: my-controller
```

What you _should_ get:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator-deployment: my-controller
  name: operator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      operator: my-controller
  template:
    metadata:
      labels:
        operator: my-controller
```
