### ISSUE TITLE
CRD generated for V1Pod in mutating webhook

### ISSUE THREAD

**Issue by jefflill** [buehler/dotnet-operator-sdk#371]
**Describe the bug**
When defining a mutating webhook for the standard KubernetesClient `V1Pod` resource, the KubeOps **generator** command creates a **crds/pods_.yaml** file.

KubeOps: **v6.4.2**

**To Reproduce**

1. Add a class that implements `IMutationWebhook<V1Pod>` to your operator.
2. Build your operator project.
3. Notice the new **crds/pods_,yaml**:

    ```
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: pods.
    spec:
      group: ''
      names:
        kind: Pod
        listKind: PodList
        plural: pods
        singular: pod
      scope: Namespaced
      versions:
      - name: v1
        schema:
          openAPIV3Schema:
            type: object
            x-kubernetes-embedded-resource: true
            x-kubernetes-preserve-unknown-fields: true
        served: true
        storage: true
        subresources:
          status: {}
    ```

**Expected behavior**
I'm not expecting to see CRDs generated for standard Kubernetes resources.

I think the problem might be that you're treating the custom resource type reference in the class implementing `IMutationWebhook<V1Pod>` as a custom resource defined in the assembly even though it's not actually defined there.

This really isn't impacting us because we're customizing our own deployment related manifests but this will probably impact others.
