### ISSUE TITLE
Operator Deployment Never Goes into Ready State

### ISSUE THREAD

**Issue by hemantkathuria** [buehler/dotnet-operator-sdk#462]
I am on ASP.Net 6.0 and using KubeOps 6.3.1

I have deployed the operator on my local Kubernetes cluster. Using the basic and don't need WebHook, Finalizer etc.
builder.Services.AddKubernetesOperator();

I can see that it automatically adds the Liveness and Readiness check in Operator.yaml file. I have not added any custom IhealthCheck.

Here is what I see when I describe the deployment.

Liveness:   http-get http://:http/health delay=30s timeout=1s period=10s #success=1 #failure=3
Readiness:  http-get http://:http/health delay=15s timeout=1s period=10s #success=1 #failure=3

If I comment the Liveness and Readiness from deployment.yaml and deploy again, it works with ZERO restart.

Has anyone else faced this problem?

**Comment by buehler** [comment]
Hey @hemantkathuria

How exactly is the liveness configured in the yaml?
The default should look something like this:

```yaml
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  timeoutSeconds: 1
```
