### ISSUE TITLE
[feature]: Specify failurepolicy when MutatingWebhookConfiguration is created

### ISSUE THREAD

**Issue by EdwardCooke** [buehler/dotnet-operator-sdk#532]
### Is your feature request related to a problem? Please describe.

I'm trying to create a mutator on a pod, which works only while my operator is running. When the operator dies, for example, restarting the deployment, the pods can't be created because the `failurePolicy` is set to `Fail`, the default. When the pod starts up after changing it manually it gets reset to Fail.

### Describe the solution you would like

Have a method called on the webhook that will allow us to configure the webhook and other objects that get installed in the cluster.

**Comment by erin-allison** [comment]
I don't think having further configuration would be bad, but for your specific situation, I would simply configure the webhook in a more specific manner.

What you can do is have the webhook configured to exclude mutating anything in a select few namespaces (kube-system and whatever namespace you would be deploying your operator into), by applying a label to them (such as "IgnoreMutate") and then filtering on that:

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
webhooks:
  - name: my-webhook.example.com
    namespaceSelector:
      matchExpressions:
        - key: IgnoreMutate
          operator: NotExists
    rules:
      - operations: ["CREATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pod"]
        scope: "Namespaced"
```
