### ISSUE TITLE
[bug]: CRD Generator generates incorrect schema for V1ResourceRequirements

### ISSUE THREAD

**Issue by slacki123** [buehler/dotnet-operator-sdk#565]
### Describe the bug

Recent developments of KubernetesYaml have added a "ResourceQuantityConverter" to the deserialization which allows us to properly parse resource requirements in a format such as

```yaml
resources:
   limits:
      cpu: "1"
```

However, the generator still generates the schema in a format where the key such as "cpu" requires to be an object rather than a string.

This is perhaps linked to the issue of being able to pass own type mapper
https://github.com/buehler/dotnet-operator-sdk/issues/396

From my investigation this looks like a bug, but I might as well missed something. I don't suppose there's a simple way to generate the CRD schema in the desired way (see below)

### To reproduce

1. Create a custom resource that has one a property type "V1ResourceRequirements" anywhere
2. Run the generator
3. See that the schema generated is the following, which is incorrect:
```yaml
                        resources:
                          properties:
                            limits:
                              additionalProperties:
                                properties:
                                  format:
                                    enum:
                                    - DecimalExponent
                                    - BinarySI
                                    - DecimalSI
                                    type: string
                                  value:
                                    type: string
                                type: object
                              type: object
```                           

it requires the "limits" field to contain a property value object with a "format" and a "value" key, but instead we want to directly map to a string which is the value. This is because the type that is being deserialised here is Dictionary\<string, ResourceQuantity\>

### Expected behavior

Generated schema should be customizable, the desired schema would be

```yaml
                        resources:
                          properties:
                            limits:
                               type: object
                               x-kubernetes-preserve-unknown-fields: true
```                   

Which is same as deserialising from type Dictionary\<string, string\> 

### Additional Context

Please let me know if there's a simple workaround for this or should I spend more time thinking about the solution, thanks!
