### ISSUE TITLE
[bug]: range (minimum/maximum) attributes generate a yaml value in current culture.

### ISSUE THREAD

**Issue by SGStino** [buehler/dotnet-operator-sdk#581]
### Describe the bug

When using the range attributes, the generated CRD always contain decimal values, but generated in the culture of the OS.
Which is invalid, as yaml only accepts a decimal point, and some cultures use decimal commas.

### To reproduce

```
 [RangeMinimum(Minimum = byte.MinValue), RangeMaximum(Maximum = byte.MaxValue)]
 public int MyProperty {get; set;}
``` 
generates
```
myProperty: 
    exclusiveMaximum: false
    exclusiveMinimum: false
    format: int32
    maximum: 255,0
    minimum: 0,0
    type: integer
```
in culture nl-BE

### Expected behavior

I'd expect it to generate Invariant Culture numbers:
```
myProperty: 
    exclusiveMaximum: false
    exclusiveMinimum: false
    format: int32
    maximum: 255.0
    minimum: 0.0
    type: integer
```
and for integers i'd even expect:
```
myProperty: 
    exclusiveMaximum: false
    exclusiveMinimum: false
    format: int32
    maximum: 255
    minimum: 0
    type: integer
```
