### ISSUE TITLE
Support (nullable) unsigned primitive numbers (or throw during CRD generation).

### ISSUE THREAD

**Issue by TeunKooijman** [buehler/dotnet-operator-sdk#75]
Currently it seems that the CRD generation process does not support (nullable) unsiged primitive numbers, in the sense that it omits the `type` property entirely, resulting in error messages such as:

 `CustomResourceDefinition.apiextensions.k8s.io "mycrd.com" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[deleteRetentionMs].type: Required value: must not be empty for specified object fields`

I.e. the OAS3 spec is generated as follows:

```
        openAPIV3Schema:
          spec:
            properties:
              deleteRetentionMs:
                nullable: true
```

For an entity such as:

```
    public class MyEntity
    {
        public ulong? DeleteRetentionMs { get; set; }
    }
```
