### ISSUE TITLE
[bug]: SAN in Certificate for Service is incorrect

### ISSUE THREAD

**Issue by YC** [buehler/dotnet-operator-sdk#769]
### Describe the bug

The first SAN in `svc.pem` does not seem to match name of service. 

### To reproduce

1. In `examples\WebhookOperator` directory
2. `KubeOps.Cli.exe gen operator namepassedin --out config`
3. `kubectl kustomize config/ -o combined.yaml`
4. The output is follows:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    operator: namepassedin
  name: namepassedin-operator
  namespace: namepassedin-system
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    operator: namepassedin
    operator-deployment: kubernetes-operator
```
5. The certificate `svc.pem`, when viewed with `openssl`:
```
X509v3 Subject Alternative Name:
DNS:namepassedin.namepassedin-system.svc, DNS:*.namepassedin-system.svc, DNS:*.svc
```

### Expected behavior

I believe the first SAN should be `namepassedin-operator.namepassedin-system.svc`. 
Also, I wonder if the other 2 are needed?

### Additional Context

Reproduced in: v9.1.1
