### ISSUE TITLE
[bug]: CRD transpiler outputs `nullable: false` which causes ArgoCD to fail to sync

### ISSUE THREAD

**Issue by robertcoltheart** [buehler/dotnet-operator-sdk#818]
### Describe the bug

Not sure why, but ArgoCD has trouble syncing CRDs that have `nullable: false` in them, which is the default value for a CRD. The fix for this would be to only output when `nullable: true`. 

### To reproduce

See below CRD:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customs.ns.home.com
spec:
  group: ns.home.com
  names:
    kind: Custom
    listKind: CustomList
    plural: customs
    singular: custom
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              nullable: false
              properties:
                prop1:
                  nullable: false
                  type: string
              required:
                - prop1
              type: object
          type: object
      served: true
      storage: true
```
