### ISSUE TITLE
[feature]: Remove commonLabels in favour of the more modern kustomize approach.

### ISSUE THREAD

**Issue by ewassef** [buehler/dotnet-operator-sdk#854]
### Is your feature request related to a problem? Please describe.

Remove commonLabels in favour of the more modern kustomize approach.

### Describe the solution you would like

Change the kustomization yaml from :

```yaml
commonLabels:
  key: value
```
to 
```yaml
labels:
- pairs:
     key: value
  includeSelectors: true
```
