### ISSUE TITLE
[bug]: Incorrect YAML structure generated for labels in kustomization.yaml

### ISSUE THREAD

**Issue by ChrisRichner** [buehler/dotnet-operator-sdk#868]
### Describe the bug

Hi there,

I'm encountering an issue where the generated `kustomization.yaml` produces an incorrect structure for the `labels` field.

### ❌ Current Output (Invalid):
```yaml
labels:
  pairs:
  - pairs:
      operator: loadtest
    includeSelectors: true
```

### ✅ Expected Output:
```yaml
labels:
- pairs:
    operator: loadtest
  includeSelectors: true
```

As you can see, the current output includes an extra nested `pairs` key, which results in an invalid Kustomize structure. This causes errors during `kubectl apply -k` or `kustomize build`, such as:

```
error: invalid Kustomization: json: cannot unmarshal object into Go struct field Kustomization.labels of type []types.Label
```

This seems to be caused by how the object model is being serialized — specifically, a nested `pairs` inside another `pairs` list.

Thanks in advance!

### To reproduce

using kubeops.cli' (version '9.3.0')

### Expected behavior

 Generating valid and desired output like

### ✅ Expected Output:
```yaml
labels:
- pairs:
    operator: loadtest
  includeSelectors: true
```
 

### Additional Context

Maybe caused by https://github.com/buehler/dotnet-operator-sdk/pull/856

Pool: Azure Pipelines
Image: ubuntu-latest
.NET Core sdk version 9.0.203

**Comment by ChrisRichner** [comment]
@ewassef FYI

**Comment by ewassef** [comment]
Good catch. Thank you for the ping. I submit a fix and will try to get out resolved asap

**Comment by ChrisRichner** [comment]
Thanks for the update! I just tried the new version and ran into the following error:

```yaml
labels:
  includeSelectors: true
  pairs:
    operator: loadtest
```

```
error: invalid Kustomization: json: cannot unmarshal object into Go struct field Kustomization.labels of type []types.Label
```

Looks to me that the Expected Output is still not generated by the fixed Version.

```yaml
labels:
  - includeSelectors: true
    pairs:
      operator: loadtest
```
